server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://80.211.39.128:3310/universidad
    username: db2
    password: database2
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update                                                                                                                                                                          
      dialect: org.hibernate.dialect.MySQL5Dialect                                                                                                                                                                                                                                                                                                                           
    generate-ddl: true